### ISSUE TITLE
[BULMA] thème selection

### ISSUE THREAD

**Issue by ornech** [ornech/gestion_stage#101]
Déterminer un moyen pour proposer de passer du thème light ou dark (peut-être depuis la page de login ?)

**Comment by ornech** [comment]
Pour offrir aux utilisateurs la possibilité de changer de thème (light ou dark) sur votre site, vous pouvez envisager les étapes suivantes :

- Ajoutez une option de sélection de thème dans l'interface utilisateur, par exemple dans les paramètres du profil utilisateur ou dans une page de préférences. Cela pourrait aussi être sur la page de connexion si vous voulez que cette option soit accessible avant la connexion.
- Stockez le choix de l'utilisateur dans un cookie ou dans la base de données de votre application afin de pouvoir récupérer cette préférence à chaque fois que l'utilisateur revient sur votre site.
- Utilisez cette préférence pour déterminer quel fichier CSS charger (ou quelles règles CSS appliquer) lorsque vous générez la page.

En termes de code, voici un exemple basique de comment cela pourrait être fait en JavaScript et CSS :

```javascript
// Supposons que vous ayez un bouton ou un autre élément d'interface utilisateur permettant à l'utilisateur de basculer entre les thèmes clair et sombre.
let toggleThemeButton = document.getElementById('toggleThemeButton');

// Vous pouvez alors ajouter un gestionnaire d'événements à ce bouton pour changer le thème lorsque l'utilisateur clique dessus.
toggleThemeButton.addEventListener('click', function() {
  // Basculer entre le thème clair et sombre.
  if (document.body.classList.contains('dark-theme')) {
    document.body.classList.remove('dark-theme');
    document.body.classList.add('light-theme');
  } else {
    document.body.classList.remove('light-theme');
    document.body.classList.add('dark-theme');
  }
});
```

Et en CSS :

```css
/* Définir les couleurs pour le thème clair. */
.light-theme {
  --background-color: #ffffff;
  --text-color: #000000;
}

/* Définir les couleurs pour le thème sombre. */
.dark-theme {
  --background-color: #000000;
  --text-color: #ffffff;
}

body {
  background-color: var(--background-color);
  color: var(--text-color);
}
```

Ceci est un exemple simplifié. Dans une application réelle, vous devriez aussi prendre en compte des éléments tels que le stockage du choix de thème de l'utilisateur et son application à chaque chargement de page.
